Algoritmo "IDADES"
Var
nome1, nome2 : caractere
idade1, idade2 : inteiro
mediaIdade : real
Inicio
Escreval ("DADOS DA PRIMEIRA PESSOA")
Escreva("Nome:")
leia(nome1)
Escreva ("Idade: ")
leia(idade1)
Escreval ("DADOS DA SEGUNDA PESSOA")
Escreva("Nome:")
leia(nome2)
Escreva ("Idade: ")
leia(idade2)
    mediaIdade <- (idade1 + idade2)/2
 Escreva ("A idade média entre ",nome1, " e " ,nome2," é ",mediaIdade)
   

Fimalgoritmo