Algoritmo "Terreno"
Var
largura, comprimento , metroQuadrado, area, preco : real
Inicio
Escreval ("Digite a largura do terreno")
leia (largura)
Escreval ("Digite o comprimento do terreno")
leia (comprimento)
Escreval ("Digite o valor do metro quadrado")
leia (metroQuadrado)
    area <- largura * comprimento
    preco <- area * metroQuadrado
 Escreval ("Area = ", area)
 Escreval ("Preço do terreno ", preco)
Fimalgoritmo